
name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.Access_key_ID }}
          aws-secret-access-key: ${{ secrets.Secret_access_key }}
          aws-region: eu-north-1

      - name: Upload files to S3
        run: aws s3 sync ./ s3://static-webhosting-car --delete
